x-client-base: &client-base
  build:
    dockerfile: client/Dockerfile.client
  working_dir: /project/R
  networks: [fednet]
  entrypoint: ["Rscript", "-e",
               "plumber::plumb('plumber.R')$
                run(host='0.0.0.0', port=Sys.getenv('PORT'))"]
  environment:
    - PORT    
  depends_on: []
services:
  client1:
    <<: *client-base
    environment: { PORT: 8001 }
    ports: ["8001:8001"]        
    volumes:
      - ./client/data/data1_1.csv:/project/data/data1_1.csv:ro
      - ./client/R:/project/R:ro
  client2:
    <<: *client-base
    environment: { PORT: 8002 }
    volumes:
      - ./client/data/data1_2.csv:/project/data/data1_2.csv:ro
      - ./client/R:/project/R:ro
  client3:
    <<: *client-base
    environment: { PORT: 8003 }
    volumes:
      - ./client/data/data1_3.csv:/project/data/data1_3.csv:ro
      - ./client/R:/project/R:ro
  client4:
    <<: *client-base
    environment: { PORT: 8004 }
    volumes:
      - ./client/data/data1_4.csv:/project/data/data1_4.csv:ro
      - ./client/R:/project/R:ro
  client5:
    <<: *client-base
    environment: { PORT: 8005 }
    volumes:
      - ./client/data/data1_5.csv:/project/data/data1_5.csv:ro
      - ./client/R:/project/R:ro

  server:
    build:
      dockerfile: server/Dockerfile.server
    working_dir: /project/R
    networks: [fednet]
    depends_on:
      - client1
      - client2
      - client3
      - client4
      - client5
    volumes:
      - ./configs/server.json:/project/configs/server.json:ro
      - ./server/R:/project/R:ro # ソースコードを共通でマウント
    entrypoint: ["Rscript", "server_main.R",
                 "--config", "/project/configs/server.json"]

networks:
  fednet:
    driver: bridge
