# docker‑compose.yml
services:
  client:
    build:
      dockerfile: client/Dockerfile.client
    working_dir: /project/R
    networks:
      - fednet         
    volumes:
      - ./configs/client1.json:/project/configs/client.json:ro
      - ./client/data/data1_5.csv:/project/data/data.csv:ro
    ports:
      - "8000:8000"
    entrypoint:
      - Rscript
      - -e
      - |
        plumber::plumb('plumber.R')$
          run(host='0.0.0.0', port=8000)
    environment:
      - PORT=8000

  server:
    build:
      dockerfile: server/Dockerfile.server
    working_dir: /project/R
    networks:
      - fednet              
    depends_on:
      - client
    volumes:
      - ./configs/server.json:/project/configs/server.json:ro
    entrypoint:
      - Rscript
      - server_main.R
      - --config
      - /project/configs/server.json

networks:
  fednet:
    driver: bridge