x-client-base: &client-base
  build:
    dockerfile: client/Dockerfile.client
  working_dir: /project/R
  networks: [fednet]
  entrypoint: ["Rscript", "-e",
               "plumber::plumb('plumber.R')$
                run(host='0.0.0.0', port=Sys.getenv('PORT'))"]
  environment:
    - PORT=8000          # 全クライアントで同一でも構わない
  depends_on: []
services:
  client1:
    <<: *client-base   
    volumes:
      - ./client/data/data1_1.csv:/project/data/data1_1.csv:ro
      - ./client/R:/project/R:ro
  client2:
    <<: *client-base
    volumes:
      - ./client/data/data1_2.csv:/project/data/data1_2.csv:ro
      - ./client/R:/project/R:ro
  client3:
    <<: *client-base
    volumes:
      - ./client/data/data1_3.csv:/project/data/data1_3.csv:ro
      - ./client/R:/project/R:ro
  client4:
    <<: *client-base
    volumes:
      - ./client/data/data1_4.csv:/project/data/data1_4.csv:ro
      - ./client/R:/project/R:ro
  client5:
    <<: *client-base
    volumes:
      - ./client/data/data1_5.csv:/project/data/data1_5.csv:ro
      - ./client/R:/project/R:ro

  server:
    build:
      dockerfile: server/Dockerfile.server
    working_dir: /project/R
    networks: [fednet]
    depends_on:
      - client1
      - client2
      - client3
      - client4
      - client5
    volumes:
      - ./configs/server.json:/project/configs/server.json:ro
      - ./server/R:/project/R:ro # ソースコードを共通でマウント
      - ./logs:/project/logs
    entrypoint: ["Rscript", "server_main.R",
                 "--config", "/project/configs/server.json"]
  dashboard:
      build: # serverと全く同じbuildセクションを追加
        dockerfile: server/Dockerfile.server
      command: ["R", "-e", "shiny::runApp('/project/R/app.R', host='0.0.0.0', port=8181)"]
      ports:
        - "8181:8181" # Shinyアプリをローカルの8181ポートで公開
      networks:
        - fednet
      volumes:
        - ./server/R:/project/R:ro # serverと同じソースとログファイルを共有
        - ./logs:/project/logs
      depends_on:
        - server

networks:
  fednet:
    driver: bridge
